### ISSUE TITLE
build.py cannot build flext debug libs

### ISSUE THREAD

**Issue by cerkut** [SopiMlab/DeepLearningWithAudio#1]
Great initiative, thanks.
Unfortunately flext does not build all targets, which affects py and subsequently the whole build stalls.

    OS 10.14.6
    Xcode 11.3.1
    pd-0.50.2

The error
`/Applications/Xcode.app/Contents/Developer/usr/bin/make -f /Users/cerkut/Developer/DeepLearningWithAudio/pyext-setup/flext/buildsys/gnumake-sub.mak  PLATFORM=mac RTSYS=pd COMPILER=gcc BUILDPATH=/Users/cerkut/Developer/DeepLearningWithAudio/pyext-setup/flext/buildsys/ PKGINFO=package.txt BUILDCLASS=flext USRCONFIG=config.txt USRMAKE=build/gnumake-mac-gcc.inc TARGETMODE=debug TARGETTYPE=single DEBUG=1 _install_

/Users/cerkut/Developer/DeepLearningWithAudio/pyext-setup/flext/buildsys/mac/gnumake-gcc-targets.inc:22: warning: overriding commands for target `pd-darwin/debug-single'

/Users/cerkut/Developer/DeepLearningWithAudio/pyext-setup/flext/buildsys/mac/gnumake-gcc-targets.inc:18: warning: ignoring old commands for target `pd-darwin/debug-single'

install pd-darwin/debug-single/libflext-pd_sd.0.6.1.a /Users/cerkut/Developer/DeepLearningWithAudio/pyext-setup/build/flext/lib
install: pd-darwin/debug-single/libflext-pd_sd.0.6.1.a: No such file or directory
make[1]: *** [_install_] Error 71
make: *** [install-debug-single] Error 2
Traceback (most recent call last):
  File "build.py", line 217, in <module>
    flext_build(args=("install",))
  File "build.py", line 195, in <lambda>
    flext_build = lambda ok_codes=(0,), args=(): call_with_env(flext_build_cmd + args, flext_build_env, ok_codes)
  File "build.py", line 119, in call_with_env
    raise Exception("command exited with unexpected code {}".format(code))
Exception: command exited with unexpected code 2`

By selectively changing the flags BUILDMODE and TARGETMODE I am investigating where the error originates from, and will report. But appreciate the help if other people have the same problem.

`flext_build_env = {
    "BUILDMODE": "debug",
    #"TARGETMODE": "single",
    "FLEXT_PD_APP": pd,
    "FLEXT_INSTALL_PATH": package_dir,
    "FLEXTPREFIX": flext_prefix,
    "FLEXT_NOATTREDIT": str(int(is_purr_data))
}`

**Comment by ahihi** [comment]
i also had some trouble with debug builds, don't remember if the error was the same though. the way i got it working was to add

```
DEBUG = 1
DFLAGS += -DFLEXT_DEBUG
```

to `flext/build/gnumake-mac-gcc.inc`.
